/**
 * Supabase Database Types
 * REQ-API-006: Auto-generated TypeScript types from Supabase gen-types CLI
 *
 * This file is auto-generated by: npm run gen-types
 * Source: Supabase database schema (public schema)
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 * Re-generate types after database schema changes:
 *   npm run gen-types
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

/**
 * Database schema definition
 * This is a placeholder until you run: npm run gen-types
 *
 * After running gen-types, this will be replaced with actual table definitions
 */
export interface Database {
  public: {
    Tables: {
      // Tables will be auto-generated here by: npm run gen-types
      // Example after generation:
      // [TableName: string]: {
      //   Row: { ... }
      //   Insert: { ... }
      //   Update: { ... }
      // }
    }
    Views: {
      // Views will be auto-generated here
    }
    Functions: {
      // Functions will be auto-generated here
    }
    Enums: {
      // Enums will be auto-generated here
    }
  }
}

// Temporary empty schema for type safety
// This will be replaced by actual types after running: npm run gen-types
export type DatabaseSchema = Database['public'];
