/**
 * Supabase Types Infrastructure Tests
 * REQ-API-006: gen-types type safety verification
 */
import fs from 'fs';
import path from 'path';

describe('Supabase Types Infrastructure (REQ-API-006)', () => {
  describe('package.json scripts', () => {
    it('should have gen-types script defined', () => {
      const packageJson = require(process.cwd() + '/package.json');

      expect(packageJson.scripts).toHaveProperty('gen-types');

      // Verify script exists using bracket notation
      expect(packageJson.scripts['gen-types']).toBeDefined();
      expect(typeof packageJson.scripts['gen-types']).toBe('string');
    });
  });

  describe('Type definitions file structure', () => {
    it('src/types/supabase.ts should exist', () => {
      const typesPath = path.join(process.cwd(), 'src/types/supabase.ts');
      expect(fs.existsSync(typesPath)).toBe(true);
    });

    it('should have proper exports', () => {
      const typesPath = path.join(process.cwd(), 'src/types/supabase.ts');
      const content = fs.readFileSync(typesPath, 'utf8');

      // Verify Database interface export
      expect(content).toContain('export interface Database');
      expect(content).toContain('public:');

      // Verify Json type export
      expect(content).toContain('export type Json');
    });

    it('should have documentation for gen-types usage', () => {
      const typesPath = path.join(process.cwd(), 'src/types/supabase.ts');
      const content = fs.readFileSync(typesPath, 'utf8');

      expect(content).toContain('npm run gen-types');
      expect(content).toContain('REQ-API-006');
      expect(content).toContain('DO NOT EDIT THIS FILE DIRECTLY');
    });
  });

  describe('Type safety readiness', () => {
    it('client.ts should be ready for type application', () => {
      const clientPath = path.join(process.cwd(), 'src/lib/supabase/client.ts');
      const content = fs.readFileSync(clientPath, 'utf8');

      // Verify that Database import is commented (ready for future use)
      expect(content).toContain('REQ-API-007');
      expect(content).toContain('// import type { Database }');

      // Verify comment about gen-types
      expect(content).toContain('npm run gen-types');
    });
  });
});
